/// Input key identifiers for keyboard and mouse.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum InputKey {
    // Mouse buttons
    MouseLeft,
    MouseRight,
    MouseMiddle,
    MouseX1,
    MouseX2,

    // Modifier keys
    Shift,
    Ctrl,
    Alt,
    Meta,

    // Navigation
    Escape,
    Tab,
    Enter,
    Backspace,
    Delete,
    Insert,
    Home,
    End,
    PageUp,
    PageDown,
    ArrowUp,
    ArrowDown,
    ArrowLeft,
    ArrowRight,

    // Function keys
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,

    // Mouse wheel
    WheelUp,
    WheelDown,
    WheelLeft,
    WheelRight,

    // Printable keys
    Space,
    Key(char),
}

/// Variant of an input event.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum InputVariant {
    /// Key or button pressed down.
    Press,
    /// Key or button released.
    Release,
    /// Repeated key press (held down).
    Repeat,
    /// Mouse moved (no button state change).
    Move,
}

/// An input event.
#[derive(Clone, Debug)]
pub struct InputEvent {
    /// Which key or button.
    pub key: InputKey,
    /// Event variant (press, release, repeat).
    pub variant: InputVariant,
    /// Characters generated by this event (for text input).
    pub chars: String,
    /// Whether this is a repeated event from holding a key.
    pub is_repeat: bool,
    /// Mouse X position in panel coordinates.
    pub mouse_x: f64,
    /// Mouse Y position in panel coordinates.
    pub mouse_y: f64,
    /// Modifier key states at the time of the event.
    pub shift: bool,
    pub ctrl: bool,
    pub alt: bool,
    pub meta: bool,
}

impl InputEvent {
    pub fn press(key: InputKey) -> Self {
        Self {
            key,
            variant: InputVariant::Press,
            chars: String::new(),
            is_repeat: false,
            mouse_x: 0.0,
            mouse_y: 0.0,
            shift: false,
            ctrl: false,
            alt: false,
            meta: false,
        }
    }

    pub fn release(key: InputKey) -> Self {
        Self {
            key,
            variant: InputVariant::Release,
            chars: String::new(),
            is_repeat: false,
            mouse_x: 0.0,
            mouse_y: 0.0,
            shift: false,
            ctrl: false,
            alt: false,
            meta: false,
        }
    }

    pub fn with_chars(mut self, chars: &str) -> Self {
        self.chars = chars.to_string();
        self
    }

    pub fn with_mouse(mut self, x: f64, y: f64) -> Self {
        self.mouse_x = x;
        self.mouse_y = y;
        self
    }

    pub fn with_modifiers(mut self, state: &super::InputState) -> Self {
        self.shift = state.shift();
        self.ctrl = state.ctrl();
        self.alt = state.alt();
        self.meta = state.meta();
        self
    }

    pub fn with_shift(mut self) -> Self {
        self.shift = true;
        self
    }

    pub fn with_ctrl(mut self) -> Self {
        self.ctrl = true;
        self
    }

    pub fn with_shift_ctrl(mut self) -> Self {
        self.shift = true;
        self.ctrl = true;
        self
    }
}
